// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDEwAlnqc9wNbWonPXn01xaW8JI0lQ5Q',
    appId: '1:457592170401:web:8440dc8d651c036b4e4de0',
    messagingSenderId: '457592170401',
    projectId: 'fir-auth-28-05',
    authDomain: 'fir-auth-28-05.firebaseapp.com',
    storageBucket: 'fir-auth-28-05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt7SNpgrPqGsK-FmpVI6Qe-G9oq61Gfek',
    appId: '1:457592170401:android:93a2d18e245491b04e4de0',
    messagingSenderId: '457592170401',
    projectId: 'fir-auth-28-05',
    storageBucket: 'fir-auth-28-05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtoUkgCvFnaUEf9aUHrmlqttW2cOi4t4',
    appId: '1:457592170401:ios:573dc0de0b6490dc4e4de0',
    messagingSenderId: '457592170401',
    projectId: 'fir-auth-28-05',
    storageBucket: 'fir-auth-28-05.appspot.com',
    iosBundleId: 'com.example.firebase285',
  );
}
